[2023-11-05T02:07:06.009+0000] {processor.py:157} INFO - Started process (PID=36332) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:06.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-05T02:07:06.032+0000] {logging_mixin.py:151} INFO - [2023-11-05T02:07:06.030+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:06.213+0000] {logging_mixin.py:151} INFO - [2023-11-05T02:07:06.181+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-05T02:07:06.229+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:06.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.357 seconds
[2023-11-05T02:07:36.926+0000] {processor.py:157} INFO - Started process (PID=36394) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:36.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-05T02:07:36.941+0000] {logging_mixin.py:151} INFO - [2023-11-05T02:07:36.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:37.021+0000] {logging_mixin.py:151} INFO - [2023-11-05T02:07:37.015+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-05T02:07:37.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-05T02:07:37.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.140 seconds
